# Alles wat niet hashed is werkt 100% De rest ben ik aan het veranderen/maken/verbeteren


# - name: "Include de Ansible-Vault file."
#   include_vars:
#     file: group_vars/WindowsServer/vault.yml
#   no_log: true

- name: " Include yml met basic tasks"
  ansible.builtin.include_tasks:
    file: include/linux/start.yml

- name: " Include yml met adding users"
  ansible.builtin.include_tasks:
    file: include/linux/users.yml

# - name: " Include yml met UFW install / config"
#   ansible.builtin.include_tasks:
#     file: include/linux/ufw.yml

# - name: "Adding SSHGuard"
#   ansible.builtin.include_tasks:
#     file: include/linux/SSHGuard.yml

# - name: " Include yml met Backup "
#   ansible.builtin.include_tasks:
#     file: include/linux/backup.yml
