- name: "Include de Ansible-Vault file."
  include_vars:
    file: ../../../group_vars/WindowsServer/vault.yml
  no_log: true

- name: " Include de powershell script om OpenSSH te installeren"
  ansible.builtin.include_tasks:
    file: ../../../include/windows/ssh.yml

- name: Installeer de volgende rollen.
  win_feature:
    name: "{{ item }}"
    state: present
  loop:
    - AD-Domain-Services
    - DHCP
    - DNS
    - WDS
  when: ansible_distribution_version >= "10.0"

- name: " Include de configuraties over Active Domain Name Services. " 
  ansible.builtin.include_tasks:
    file: ../../../include/windows/adds.yml